/**
 * The builder chrome's icons, drawn as inline SVG.
 *
 * The chrome used to draw icons as Material Symbols ligatures: a span holding
 * the icon's name ("content_copy"), turned into a glyph by a font. Until that
 * font arrived, or when it never did, every control showed letters. An inline
 * SVG has nothing to wait for.
 *
 * Call sites keep the Material Symbols name they always used, so data that
 * names an icon (templates, the component library, menus, toasts) needs no
 * change. nodes.ts (generated by scripts/generate-chrome-icons.mjs) holds the
 * drawing of the closest lucide icon for each name. A name with no entry
 * draws a neutral mark, never its letters.
 *
 * The icon is one em square and takes the current colour, exactly as the
 * glyph did: `font-size` (a class or an inline style) still sets its size.
 * The size and the alignment live in `.chrome-icon` (globals.css).
 *
 * Canvas content is different: an icon inside a block is part of the design
 * system on show (Material 3 and uoaui DS use Material Symbols), so blocks
 * keep the font, which is served from this origin (src/fonts).
 */
import { CHROME_ICON_FALLBACK, CHROME_ICON_NODES, type ChromeIconNode } from "./nodes";

export type { ChromeIconNode };

export function hasChromeIcon(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(CHROME_ICON_NODES, name);
}

export function chromeIconNode(name: string): ChromeIconNode {
  return hasChromeIcon(name) ? CHROME_ICON_NODES[name] : CHROME_ICON_FALLBACK;
}

export function chromeIconNames(): string[] {
  return Object.keys(CHROME_ICON_NODES);
}

/* Lucide draws on a 24 unit grid; 1.8 reads as the same weight as the 400
   weight glyphs it replaces at the chrome's 14 to 20px sizes, and matches the
   Present bar. */
export const CHROME_ICON_STROKE = 1.8;

/** The attributes every chrome icon's <svg> carries. */
export function chromeIconAttrs(name: string, filled = false): Record<string, string> {
  return {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 24",
    width: "1em",
    height: "1em",
    fill: filled ? "currentColor" : "none",
    stroke: "currentColor",
    "stroke-width": String(CHROME_ICON_STROKE),
    "stroke-linecap": "round",
    "stroke-linejoin": "round",
    "aria-hidden": "true",
    focusable: "false",
    "data-icon": name,
    ...(hasChromeIcon(name) ? {} : { "data-icon-missing": "true" }),
  };
}

const SVG_NS = "http://www.w3.org/2000/svg";

/** The same icon for code with no React (the toast). */
export function createChromeIconElement(name: string, className?: string): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg");
  for (const [key, value] of Object.entries(chromeIconAttrs(name))) {
    if (key !== "xmlns") svg.setAttribute(key, value);
  }
  svg.setAttribute("class", className ? `chrome-icon ${className}` : "chrome-icon");
  for (const [tag, attrs] of chromeIconNode(name)) {
    const shape = document.createElementNS(SVG_NS, tag);
    for (const [key, value] of Object.entries(attrs)) shape.setAttribute(key, value);
    svg.appendChild(shape);
  }
  return svg;
}
