/* Generated by scripts/generate-chrome-icons.mjs from lucide-react 1.8.0. Do not edit.

   The drawings are lucide's (https://lucide.dev), used under the ISC licence.
   Copyright (c) 2026 Lucide Icons and Contributors. Some icons derive from
   Feather, copyright (c) 2013-present Cole Bemis (MIT). Permission to use,
   copy, modify, and/or distribute this software for any purpose with or
   without fee is hereby granted, provided that the above copyright notice
   and this permission notice appear in all copies. Full text, kept beside
   this file: LICENSE-lucide.txt. */

export type ChromeIconNode = readonly (readonly [tag: string, attrs: Readonly<Record<string, string>>])[];

const ALIGN_CENTER_HORIZONTAL: ChromeIconNode = [["path",{"d":"M2 12h20"}],["path",{"d":"M10 16v4a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-4"}],["path",{"d":"M10 8V4a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v4"}],["path",{"d":"M20 16v1a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2v-1"}],["path",{"d":"M14 8V7c0-1.1.9-2 2-2h2a2 2 0 0 1 2 2v1"}]];
const ALIGN_CENTER_VERTICAL: ChromeIconNode = [["path",{"d":"M12 2v20"}],["path",{"d":"M8 10H4a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2h4"}],["path",{"d":"M16 10h4a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-4"}],["path",{"d":"M8 20H7a2 2 0 0 1-2-2v-2c0-1.1.9-2 2-2h1"}],["path",{"d":"M16 14h1a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2h-1"}]];
const ALIGN_END_HORIZONTAL: ChromeIconNode = [["rect",{"width":"6","height":"16","x":"4","y":"2","rx":"2"}],["rect",{"width":"6","height":"9","x":"14","y":"9","rx":"2"}],["path",{"d":"M22 22H2"}]];
const ALIGN_END_VERTICAL: ChromeIconNode = [["rect",{"width":"16","height":"6","x":"2","y":"4","rx":"2"}],["rect",{"width":"9","height":"6","x":"9","y":"14","rx":"2"}],["path",{"d":"M22 22V2"}]];
const ALIGN_JUSTIFY: ChromeIconNode = [["path",{"d":"M3 5h18"}],["path",{"d":"M3 12h18"}],["path",{"d":"M3 19h18"}]];
const ALIGN_START_HORIZONTAL: ChromeIconNode = [["rect",{"width":"6","height":"16","x":"4","y":"6","rx":"2"}],["rect",{"width":"6","height":"9","x":"14","y":"6","rx":"2"}],["path",{"d":"M22 2H2"}]];
const ALIGN_START_VERTICAL: ChromeIconNode = [["rect",{"width":"9","height":"6","x":"6","y":"14","rx":"2"}],["rect",{"width":"16","height":"6","x":"6","y":"4","rx":"2"}],["path",{"d":"M2 2v20"}]];
const APP_WINDOW: ChromeIconNode = [["rect",{"x":"2","y":"4","width":"20","height":"16","rx":"2"}],["path",{"d":"M10 4v4"}],["path",{"d":"M2 8h20"}],["path",{"d":"M6 4v4"}]];
const ARROW_DOWN: ChromeIconNode = [["path",{"d":"M12 5v14"}],["path",{"d":"m19 12-7 7-7-7"}]];
const ARROW_DOWN_TO_LINE: ChromeIconNode = [["path",{"d":"M12 17V3"}],["path",{"d":"m6 11 6 6 6-6"}],["path",{"d":"M19 21H5"}]];
const ARROW_LEFT_RIGHT: ChromeIconNode = [["path",{"d":"M8 3 4 7l4 4"}],["path",{"d":"M4 7h16"}],["path",{"d":"m16 21 4-4-4-4"}],["path",{"d":"M20 17H4"}]];
const ARROW_LEFT_TO_LINE: ChromeIconNode = [["path",{"d":"M3 19V5"}],["path",{"d":"m13 6-6 6 6 6"}],["path",{"d":"M7 12h14"}]];
const ARROW_RIGHT: ChromeIconNode = [["path",{"d":"M5 12h14"}],["path",{"d":"m12 5 7 7-7 7"}]];
const ARROW_UP: ChromeIconNode = [["path",{"d":"m5 12 7-7 7 7"}],["path",{"d":"M12 19V5"}]];
const ARROW_UP_TO_LINE: ChromeIconNode = [["path",{"d":"M5 3h14"}],["path",{"d":"m18 13-6-6-6 6"}],["path",{"d":"M12 7v14"}]];
const BADGE: ChromeIconNode = [["path",{"d":"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"}]];
const BADGE_CHECK: ChromeIconNode = [["path",{"d":"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"}],["path",{"d":"m9 12 2 2 4-4"}]];
const BAN: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M4.929 4.929 19.07 19.071"}]];
const BELL: ChromeIconNode = [["path",{"d":"M10.268 21a2 2 0 0 0 3.464 0"}],["path",{"d":"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"}]];
const BINARY: ChromeIconNode = [["rect",{"x":"14","y":"14","width":"4","height":"6","rx":"2"}],["rect",{"x":"6","y":"4","width":"4","height":"6","rx":"2"}],["path",{"d":"M6 20h4"}],["path",{"d":"M14 10h4"}],["path",{"d":"M6 14h2v6"}],["path",{"d":"M14 4h2v6"}]];
const BLOCKS: ChromeIconNode = [["path",{"d":"M10 22V7a1 1 0 0 0-1-1H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5a1 1 0 0 0-1-1H2"}],["rect",{"x":"14","y":"2","width":"8","height":"8","rx":"1"}]];
const BOOKMARK: ChromeIconNode = [["path",{"d":"M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"}]];
const BRACES: ChromeIconNode = [["path",{"d":"M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1"}],["path",{"d":"M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1"}]];
const CALENDAR: ChromeIconNode = [["path",{"d":"M8 2v4"}],["path",{"d":"M16 2v4"}],["rect",{"width":"18","height":"18","x":"3","y":"4","rx":"2"}],["path",{"d":"M3 10h18"}]];
const CHART_AREA: ChromeIconNode = [["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["path",{"d":"M7 11.207a.5.5 0 0 1 .146-.353l2-2a.5.5 0 0 1 .708 0l3.292 3.292a.5.5 0 0 0 .708 0l4.292-4.292a.5.5 0 0 1 .854.353V16a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1z"}]];
const CHART_CANDLESTICK: ChromeIconNode = [["path",{"d":"M9 5v4"}],["rect",{"width":"4","height":"6","x":"7","y":"9","rx":"1"}],["path",{"d":"M9 15v2"}],["path",{"d":"M17 3v2"}],["rect",{"width":"4","height":"8","x":"15","y":"5","rx":"1"}],["path",{"d":"M17 13v3"}],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}]];
const CHART_COLUMN: ChromeIconNode = [["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["path",{"d":"M18 17V9"}],["path",{"d":"M13 17V5"}],["path",{"d":"M8 17v-3"}]];
const CHART_COLUMN_BIG: ChromeIconNode = [["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["rect",{"x":"15","y":"5","width":"4","height":"12","rx":"1"}],["rect",{"x":"7","y":"8","width":"4","height":"9","rx":"1"}]];
const CHART_COLUMN_DECREASING: ChromeIconNode = [["path",{"d":"M13 17V9"}],["path",{"d":"M18 17v-3"}],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["path",{"d":"M8 17V5"}]];
const CHART_COLUMN_STACKED: ChromeIconNode = [["path",{"d":"M11 13H7"}],["path",{"d":"M19 9h-4"}],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["rect",{"x":"15","y":"5","width":"4","height":"12","rx":"1"}],["rect",{"x":"7","y":"8","width":"4","height":"9","rx":"1"}]];
const CHART_GANTT: ChromeIconNode = [["path",{"d":"M10 6h8"}],["path",{"d":"M12 16h6"}],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["path",{"d":"M8 11h7"}]];
const CHART_LINE: ChromeIconNode = [["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["path",{"d":"m19 9-5 5-4-4-3 3"}]];
const CHART_NO_AXES_COLUMN: ChromeIconNode = [["path",{"d":"M5 21v-6"}],["path",{"d":"M12 21V3"}],["path",{"d":"M19 21V9"}]];
const CHART_NO_AXES_COMBINED: ChromeIconNode = [["path",{"d":"M12 16v5"}],["path",{"d":"M16 14v7"}],["path",{"d":"M20 10v11"}],["path",{"d":"m22 3-8.646 8.646a.5.5 0 0 1-.708 0L9.354 8.354a.5.5 0 0 0-.707 0L2 15"}],["path",{"d":"M4 18v3"}],["path",{"d":"M8 14v7"}]];
const CHART_PIE: ChromeIconNode = [["path",{"d":"M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z"}],["path",{"d":"M21.21 15.89A10 10 0 1 1 8 2.83"}]];
const CHART_SCATTER: ChromeIconNode = [["circle",{"cx":"7.5","cy":"7.5","r":".5","fill":"currentColor"}],["circle",{"cx":"18.5","cy":"5.5","r":".5","fill":"currentColor"}],["circle",{"cx":"11.5","cy":"11.5","r":".5","fill":"currentColor"}],["circle",{"cx":"7.5","cy":"16.5","r":".5","fill":"currentColor"}],["circle",{"cx":"17.5","cy":"14.5","r":".5","fill":"currentColor"}],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}]];
const CHART_SPLINE: ChromeIconNode = [["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}],["path",{"d":"M7 16c.5-2 1.5-7 4-7 2 0 2 3 4 3 2.5 0 4.5-5 5-7"}]];
const CHECK: ChromeIconNode = [["path",{"d":"M20 6 9 17l-5-5"}]];
const CHEVRON_DOWN: ChromeIconNode = [["path",{"d":"m6 9 6 6 6-6"}]];
const CHEVRON_LEFT: ChromeIconNode = [["path",{"d":"m15 18-6-6 6-6"}]];
const CHEVRON_RIGHT: ChromeIconNode = [["path",{"d":"m9 18 6-6-6-6"}]];
const CHEVRON_UP: ChromeIconNode = [["path",{"d":"m18 15-6-6-6 6"}]];
const CHEVRONS_DOWN_UP: ChromeIconNode = [["path",{"d":"m7 20 5-5 5 5"}],["path",{"d":"m7 4 5 5 5-5"}]];
const CHEVRONS_UP_DOWN: ChromeIconNode = [["path",{"d":"m7 15 5 5 5-5"}],["path",{"d":"m7 9 5-5 5 5"}]];
const CIRCLE: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}]];
const CIRCLE_ALERT: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["line",{"x1":"12","x2":"12","y1":"8","y2":"12"}],["line",{"x1":"12","x2":"12.01","y1":"16","y2":"16"}]];
const CIRCLE_CHECK: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"m9 12 2 2 4-4"}]];
const CIRCLE_CHEVRON_DOWN: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"m16 10-4 4-4-4"}]];
const CIRCLE_DASHED: ChromeIconNode = [["path",{"d":"M10.1 2.182a10 10 0 0 1 3.8 0"}],["path",{"d":"M13.9 21.818a10 10 0 0 1-3.8 0"}],["path",{"d":"M17.609 3.721a10 10 0 0 1 2.69 2.7"}],["path",{"d":"M2.182 13.9a10 10 0 0 1 0-3.8"}],["path",{"d":"M20.279 17.609a10 10 0 0 1-2.7 2.69"}],["path",{"d":"M21.818 10.1a10 10 0 0 1 0 3.8"}],["path",{"d":"M3.721 6.391a10 10 0 0 1 2.7-2.69"}],["path",{"d":"M6.391 20.279a10 10 0 0 1-2.69-2.7"}]];
const CIRCLE_DOT: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["circle",{"cx":"12","cy":"12","r":"1"}]];
const CIRCLE_PLUS: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M8 12h8"}],["path",{"d":"M12 8v8"}]];
const CIRCLE_USER: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["circle",{"cx":"12","cy":"10","r":"3"}],["path",{"d":"M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662"}]];
const CLIPBOARD_CHECK: ChromeIconNode = [["rect",{"width":"8","height":"4","x":"8","y":"2","rx":"1","ry":"1"}],["path",{"d":"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"}],["path",{"d":"m9 14 2 2 4-4"}]];
const CLIPBOARD_LIST: ChromeIconNode = [["rect",{"width":"8","height":"4","x":"8","y":"2","rx":"1","ry":"1"}],["path",{"d":"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"}],["path",{"d":"M12 11h4"}],["path",{"d":"M12 16h4"}],["path",{"d":"M8 11h.01"}],["path",{"d":"M8 16h.01"}]];
const CODE: ChromeIconNode = [["path",{"d":"m16 18 6-6-6-6"}],["path",{"d":"m8 6-6 6 6 6"}]];
const COLUMNS_2: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M12 3v18"}]];
const COLUMNS_3: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M9 3v18"}],["path",{"d":"M15 3v18"}]];
const COLUMNS_4: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M7.5 3v18"}],["path",{"d":"M12 3v18"}],["path",{"d":"M16.5 3v18"}]];
const CONTACT: ChromeIconNode = [["path",{"d":"M16 2v2"}],["path",{"d":"M7 22v-2a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v2"}],["path",{"d":"M8 2v2"}],["circle",{"cx":"12","cy":"11","r":"3"}],["rect",{"x":"3","y":"4","width":"18","height":"18","rx":"2"}]];
const CONTRAST: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M12 18a6 6 0 0 0 0-12v12z"}]];
const COPY: ChromeIconNode = [["rect",{"width":"14","height":"14","x":"8","y":"8","rx":"2","ry":"2"}],["path",{"d":"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}]];
const CREDIT_CARD: ChromeIconNode = [["rect",{"width":"20","height":"14","x":"2","y":"5","rx":"2"}],["line",{"x1":"2","x2":"22","y1":"10","y2":"10"}]];
const DATABASE: ChromeIconNode = [["ellipse",{"cx":"12","cy":"5","rx":"9","ry":"3"}],["path",{"d":"M3 5V19A9 3 0 0 0 21 19V5"}],["path",{"d":"M3 12A9 3 0 0 0 21 12"}]];
const DOWNLOAD: ChromeIconNode = [["path",{"d":"M12 15V3"}],["path",{"d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"}],["path",{"d":"m7 10 5 5 5-5"}]];
const ELLIPSIS: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"1"}],["circle",{"cx":"19","cy":"12","r":"1"}],["circle",{"cx":"5","cy":"12","r":"1"}]];
const EXTERNAL_LINK: ChromeIconNode = [["path",{"d":"M15 3h6v6"}],["path",{"d":"M10 14 21 3"}],["path",{"d":"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"}]];
const EYE: ChromeIconNode = [["path",{"d":"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"}],["circle",{"cx":"12","cy":"12","r":"3"}]];
const FILE_UP: ChromeIconNode = [["path",{"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}],["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"}],["path",{"d":"M12 12v6"}],["path",{"d":"m15 15-3-3-3 3"}]];
const FILE_USER: ChromeIconNode = [["path",{"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}],["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"}],["path",{"d":"M16 22a4 4 0 0 0-8 0"}],["circle",{"cx":"12","cy":"15","r":"3"}]];
const FOLD_VERTICAL: ChromeIconNode = [["path",{"d":"M12 22v-6"}],["path",{"d":"M12 8V2"}],["path",{"d":"M4 12H2"}],["path",{"d":"M10 12H8"}],["path",{"d":"M16 12h-2"}],["path",{"d":"M22 12h-2"}],["path",{"d":"m15 19-3-3-3 3"}],["path",{"d":"m15 5-3 3-3-3"}]];
const FOLDER_ARCHIVE: ChromeIconNode = [["circle",{"cx":"15","cy":"19","r":"2"}],["path",{"d":"M20.9 19.8A2 2 0 0 0 22 18V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h5.1"}],["path",{"d":"M15 11v-1"}],["path",{"d":"M15 17v-2"}]];
const FOLDER_OPEN: ChromeIconNode = [["path",{"d":"m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"}]];
const FUNNEL: ChromeIconNode = [["path",{"d":"M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z"}]];
const GAUGE: ChromeIconNode = [["path",{"d":"m12 14 4-4"}],["path",{"d":"M3.34 19a10 10 0 1 1 17.32 0"}]];
const GLOBE: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"}],["path",{"d":"M2 12h20"}]];
const GRID_2X2: ChromeIconNode = [["path",{"d":"M12 3v18"}],["path",{"d":"M3 12h18"}],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"}]];
const GRID_3X3: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M3 9h18"}],["path",{"d":"M3 15h18"}],["path",{"d":"M9 3v18"}],["path",{"d":"M15 3v18"}]];
const GRIP_VERTICAL: ChromeIconNode = [["circle",{"cx":"9","cy":"12","r":"1"}],["circle",{"cx":"9","cy":"5","r":"1"}],["circle",{"cx":"9","cy":"19","r":"1"}],["circle",{"cx":"15","cy":"12","r":"1"}],["circle",{"cx":"15","cy":"5","r":"1"}],["circle",{"cx":"15","cy":"19","r":"1"}]];
const HASH: ChromeIconNode = [["line",{"x1":"4","x2":"20","y1":"9","y2":"9"}],["line",{"x1":"4","x2":"20","y1":"15","y2":"15"}],["line",{"x1":"10","x2":"8","y1":"3","y2":"21"}],["line",{"x1":"16","x2":"14","y1":"3","y2":"21"}]];
const HEADING: ChromeIconNode = [["path",{"d":"M6 12h12"}],["path",{"d":"M6 20V4"}],["path",{"d":"M18 20V4"}]];
const HISTORY: ChromeIconNode = [["path",{"d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"}],["path",{"d":"M3 3v5h5"}],["path",{"d":"M12 7v5l4 2"}]];
const HOURGLASS: ChromeIconNode = [["path",{"d":"M5 22h14"}],["path",{"d":"M5 2h14"}],["path",{"d":"M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22"}],["path",{"d":"M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2"}]];
const HOUSE: ChromeIconNode = [["path",{"d":"M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"}],["path",{"d":"M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"}]];
const ID_CARD: ChromeIconNode = [["path",{"d":"M16 10h2"}],["path",{"d":"M16 14h2"}],["path",{"d":"M6.17 15a3 3 0 0 1 5.66 0"}],["circle",{"cx":"9","cy":"11","r":"2"}],["rect",{"x":"2","y":"5","width":"20","height":"14","rx":"2"}]];
const IMAGE: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2","ry":"2"}],["circle",{"cx":"9","cy":"9","r":"2"}],["path",{"d":"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}]];
const IMAGE_PLUS: ChromeIconNode = [["path",{"d":"M16 5h6"}],["path",{"d":"M19 2v6"}],["path",{"d":"M21 11.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7.5"}],["path",{"d":"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}],["circle",{"cx":"9","cy":"9","r":"2"}]];
const IMAGES: ChromeIconNode = [["path",{"d":"m22 11-1.296-1.296a2.4 2.4 0 0 0-3.408 0L11 16"}],["path",{"d":"M4 8a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2"}],["circle",{"cx":"13","cy":"7","r":"1","fill":"currentColor"}],["rect",{"x":"8","y":"2","width":"14","height":"14","rx":"2"}]];
const INFO: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M12 16v-4"}],["path",{"d":"M12 8h.01"}]];
const LAYOUT_DASHBOARD: ChromeIconNode = [["rect",{"width":"7","height":"9","x":"3","y":"3","rx":"1"}],["rect",{"width":"7","height":"5","x":"14","y":"3","rx":"1"}],["rect",{"width":"7","height":"9","x":"14","y":"12","rx":"1"}],["rect",{"width":"7","height":"5","x":"3","y":"16","rx":"1"}]];
const LAYOUT_GRID: ChromeIconNode = [["rect",{"width":"7","height":"7","x":"3","y":"3","rx":"1"}],["rect",{"width":"7","height":"7","x":"14","y":"3","rx":"1"}],["rect",{"width":"7","height":"7","x":"14","y":"14","rx":"1"}],["rect",{"width":"7","height":"7","x":"3","y":"14","rx":"1"}]];
const LAYOUT_PANEL_TOP: ChromeIconNode = [["rect",{"width":"18","height":"7","x":"3","y":"3","rx":"1"}],["rect",{"width":"7","height":"7","x":"3","y":"14","rx":"1"}],["rect",{"width":"7","height":"7","x":"14","y":"14","rx":"1"}]];
const LAYOUT_TEMPLATE: ChromeIconNode = [["rect",{"width":"18","height":"7","x":"3","y":"3","rx":"1"}],["rect",{"width":"9","height":"7","x":"3","y":"14","rx":"1"}],["rect",{"width":"5","height":"7","x":"16","y":"14","rx":"1"}]];
const LEAF: ChromeIconNode = [["path",{"d":"M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"}],["path",{"d":"M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"}]];
const LINK: ChromeIconNode = [["path",{"d":"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"}],["path",{"d":"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"}]];
const LIST: ChromeIconNode = [["path",{"d":"M3 5h.01"}],["path",{"d":"M3 12h.01"}],["path",{"d":"M3 19h.01"}],["path",{"d":"M8 5h13"}],["path",{"d":"M8 12h13"}],["path",{"d":"M8 19h13"}]];
const LIST_FILTER: ChromeIconNode = [["path",{"d":"M2 5h20"}],["path",{"d":"M6 12h12"}],["path",{"d":"M9 19h6"}]];
const LIST_X: ChromeIconNode = [["path",{"d":"M16 5H3"}],["path",{"d":"M11 12H3"}],["path",{"d":"M16 19H3"}],["path",{"d":"m15.5 9.5 5 5"}],["path",{"d":"m20.5 9.5-5 5"}]];
const LOADER: ChromeIconNode = [["path",{"d":"M12 2v4"}],["path",{"d":"m16.2 7.8 2.9-2.9"}],["path",{"d":"M18 12h4"}],["path",{"d":"m16.2 16.2 2.9 2.9"}],["path",{"d":"M12 18v4"}],["path",{"d":"m4.9 19.1 2.9-2.9"}],["path",{"d":"M2 12h4"}],["path",{"d":"m4.9 4.9 2.9 2.9"}]];
const LOG_IN: ChromeIconNode = [["path",{"d":"m10 17 5-5-5-5"}],["path",{"d":"M15 12H3"}],["path",{"d":"M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"}]];
const MAXIMIZE: ChromeIconNode = [["path",{"d":"M8 3H5a2 2 0 0 0-2 2v3"}],["path",{"d":"M21 8V5a2 2 0 0 0-2-2h-3"}],["path",{"d":"M3 16v3a2 2 0 0 0 2 2h3"}],["path",{"d":"M16 21h3a2 2 0 0 0 2-2v-3"}]];
const MENU: ChromeIconNode = [["path",{"d":"M4 5h16"}],["path",{"d":"M4 12h16"}],["path",{"d":"M4 19h16"}]];
const MESSAGE_SQUARE: ChromeIconNode = [["path",{"d":"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"}]];
const MESSAGE_SQUARE_DASHED: ChromeIconNode = [["path",{"d":"M14 3h2"}],["path",{"d":"M16 19h-2"}],["path",{"d":"M2 12v-2"}],["path",{"d":"M2 16v5.286a.71.71 0 0 0 1.212.502l1.149-1.149"}],["path",{"d":"M20 19a2 2 0 0 0 2-2v-1"}],["path",{"d":"M22 10v2"}],["path",{"d":"M22 6V5a2 2 0 0 0-2-2"}],["path",{"d":"M4 3a2 2 0 0 0-2 2v1"}],["path",{"d":"M8 19h2"}],["path",{"d":"M8 3h2"}]];
const MESSAGE_SQUARE_TEXT: ChromeIconNode = [["path",{"d":"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"}],["path",{"d":"M7 11h10"}],["path",{"d":"M7 15h6"}],["path",{"d":"M7 7h8"}]];
const MESSAGES_SQUARE: ChromeIconNode = [["path",{"d":"M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"}],["path",{"d":"M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1"}]];
const MINUS: ChromeIconNode = [["path",{"d":"M5 12h14"}]];
const MOON: ChromeIconNode = [["path",{"d":"M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"}]];
const MOUSE_POINTER_CLICK: ChromeIconNode = [["path",{"d":"M14 4.1 12 6"}],["path",{"d":"m5.1 8-2.9-.8"}],["path",{"d":"m6 12-1.9 2"}],["path",{"d":"M7.2 2.2 8 5.1"}],["path",{"d":"M9.037 9.69a.498.498 0 0 1 .653-.653l11 4.5a.5.5 0 0 1-.074.949l-4.349 1.041a1 1 0 0 0-.74.739l-1.04 4.35a.5.5 0 0 1-.95.074z"}]];
const MOVE: ChromeIconNode = [["path",{"d":"M12 2v20"}],["path",{"d":"m15 19-3 3-3-3"}],["path",{"d":"m19 9 3 3-3 3"}],["path",{"d":"M2 12h20"}],["path",{"d":"m5 9-3 3 3 3"}],["path",{"d":"m9 5 3-3 3 3"}]];
const MOVE_HORIZONTAL: ChromeIconNode = [["path",{"d":"m18 8 4 4-4 4"}],["path",{"d":"M2 12h20"}],["path",{"d":"m6 8-4 4 4 4"}]];
const MOVE_VERTICAL: ChromeIconNode = [["path",{"d":"M12 2v20"}],["path",{"d":"m8 18 4 4 4-4"}],["path",{"d":"m8 6 4-4 4 4"}]];
const NETWORK: ChromeIconNode = [["rect",{"x":"16","y":"16","width":"6","height":"6","rx":"1"}],["rect",{"x":"2","y":"16","width":"6","height":"6","rx":"1"}],["rect",{"x":"9","y":"2","width":"6","height":"6","rx":"1"}],["path",{"d":"M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"}],["path",{"d":"M12 12V8"}]];
const NEWSPAPER: ChromeIconNode = [["path",{"d":"M15 18h-5"}],["path",{"d":"M18 14h-8"}],["path",{"d":"M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-4 0v-9a2 2 0 0 1 2-2h2"}],["rect",{"width":"8","height":"4","x":"10","y":"6","rx":"1"}]];
const OCTAGON_ALERT: ChromeIconNode = [["path",{"d":"M12 16h.01"}],["path",{"d":"M12 8v4"}],["path",{"d":"M15.312 2a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586l-4.688-4.688A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2z"}]];
const PACKAGE: ChromeIconNode = [["path",{"d":"M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"}],["path",{"d":"M12 22V12"}],["polyline",{"points":"3.29 7 12 12 20.71 7"}],["path",{"d":"m7.5 4.27 9 5.15"}]];
const PAINT_BUCKET: ChromeIconNode = [["path",{"d":"M11 7 6 2"}],["path",{"d":"M18.992 12H2.041"}],["path",{"d":"M21.145 18.38A3.34 3.34 0 0 1 20 16.5a3.3 3.3 0 0 1-1.145 1.88c-.575.46-.855 1.02-.855 1.595A2 2 0 0 0 20 22a2 2 0 0 0 2-2.025c0-.58-.285-1.13-.855-1.595"}],["path",{"d":"m8.5 4.5 2.148-2.148a1.205 1.205 0 0 1 1.704 0l7.296 7.296a1.205 1.205 0 0 1 0 1.704l-7.592 7.592a3.615 3.615 0 0 1-5.112 0l-3.888-3.888a3.615 3.615 0 0 1 0-5.112L5.67 7.33"}]];
const PALETTE: ChromeIconNode = [["path",{"d":"M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z"}],["circle",{"cx":"13.5","cy":"6.5","r":".5","fill":"currentColor"}],["circle",{"cx":"17.5","cy":"10.5","r":".5","fill":"currentColor"}],["circle",{"cx":"6.5","cy":"12.5","r":".5","fill":"currentColor"}],["circle",{"cx":"8.5","cy":"7.5","r":".5","fill":"currentColor"}]];
const PANEL_BOTTOM: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M3 15h18"}]];
const PANEL_LEFT: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M9 3v18"}]];
const PANEL_LEFT_CLOSE: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M9 3v18"}],["path",{"d":"m16 15-3-3 3-3"}]];
const PANEL_RIGHT: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M15 3v18"}]];
const PANEL_TOP: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M3 9h18"}]];
const PANEL_TOP_DASHED: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M14 9h1"}],["path",{"d":"M19 9h2"}],["path",{"d":"M3 9h2"}],["path",{"d":"M9 9h1"}]];
const PENCIL: ChromeIconNode = [["path",{"d":"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"}],["path",{"d":"m15 5 4 4"}]];
const PENCIL_RULER: ChromeIconNode = [["path",{"d":"M13 7 8.7 2.7a2.41 2.41 0 0 0-3.4 0L2.7 5.3a2.41 2.41 0 0 0 0 3.4L7 13"}],["path",{"d":"m8 6 2-2"}],["path",{"d":"m18 16 2-2"}],["path",{"d":"m17 11 4.3 4.3c.94.94.94 2.46 0 3.4l-2.6 2.6c-.94.94-2.46.94-3.4 0L11 17"}],["path",{"d":"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"}],["path",{"d":"m15 5 4 4"}]];
const PERCENT: ChromeIconNode = [["line",{"x1":"19","x2":"5","y1":"5","y2":"19"}],["circle",{"cx":"6.5","cy":"6.5","r":"2.5"}],["circle",{"cx":"17.5","cy":"17.5","r":"2.5"}]];
const PICTURE_IN_PICTURE_2: ChromeIconNode = [["path",{"d":"M21 9V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v10c0 1.1.9 2 2 2h4"}],["rect",{"width":"10","height":"7","x":"12","y":"13","rx":"2"}]];
const PIPETTE: ChromeIconNode = [["path",{"d":"m12 9-8.414 8.414A2 2 0 0 0 3 18.828v1.344a2 2 0 0 1-.586 1.414A2 2 0 0 1 3.828 21h1.344a2 2 0 0 0 1.414-.586L15 12"}],["path",{"d":"m18 9 .4.4a1 1 0 1 1-3 3l-3.8-3.8a1 1 0 1 1 3-3l.4.4 3.4-3.4a1 1 0 1 1 3 3z"}],["path",{"d":"m2 22 .414-.414"}]];
const PLUS: ChromeIconNode = [["path",{"d":"M5 12h14"}],["path",{"d":"M12 5v14"}]];
const RADAR: ChromeIconNode = [["path",{"d":"M19.07 4.93A10 10 0 0 0 6.99 3.34"}],["path",{"d":"M4 6h.01"}],["path",{"d":"M2.29 9.62A10 10 0 1 0 21.31 8.35"}],["path",{"d":"M16.24 7.76A6 6 0 1 0 8.23 16.67"}],["path",{"d":"M12 18h.01"}],["path",{"d":"M17.99 11.66A6 6 0 0 1 15.77 16.67"}],["circle",{"cx":"12","cy":"12","r":"2"}],["path",{"d":"m13.41 10.59 5.66-5.66"}]];
const RECTANGLE_HORIZONTAL: ChromeIconNode = [["rect",{"width":"20","height":"12","x":"2","y":"6","rx":"2"}]];
const REDO_2: ChromeIconNode = [["path",{"d":"m15 14 5-5-5-5"}],["path",{"d":"M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13"}]];
const REFRESH_CW: ChromeIconNode = [["path",{"d":"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"}],["path",{"d":"M21 3v5h-5"}],["path",{"d":"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"}],["path",{"d":"M8 16H3v5"}]];
const ROCKET: ChromeIconNode = [["path",{"d":"M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"}],["path",{"d":"M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09"}],["path",{"d":"M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z"}],["path",{"d":"M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05"}]];
const ROTATE_CCW: ChromeIconNode = [["path",{"d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"}],["path",{"d":"M3 3v5h5"}]];
const ROWS_2: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M3 12h18"}]];
const ROWS_3: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M21 9H3"}],["path",{"d":"M21 15H3"}]];
const SCAN: ChromeIconNode = [["path",{"d":"M3 7V5a2 2 0 0 1 2-2h2"}],["path",{"d":"M17 3h2a2 2 0 0 1 2 2v2"}],["path",{"d":"M21 17v2a2 2 0 0 1-2 2h-2"}],["path",{"d":"M7 21H5a2 2 0 0 1-2-2v-2"}]];
const SEARCH: ChromeIconNode = [["path",{"d":"m21 21-4.34-4.34"}],["circle",{"cx":"11","cy":"11","r":"8"}]];
const SEND_HORIZONTAL: ChromeIconNode = [["path",{"d":"M3.714 3.048a.498.498 0 0 0-.683.627l2.843 7.627a2 2 0 0 1 0 1.396l-2.842 7.627a.498.498 0 0 0 .682.627l18-8.5a.5.5 0 0 0 0-.904z"}],["path",{"d":"M6 12h16"}]];
const SETTINGS: ChromeIconNode = [["path",{"d":"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"}],["circle",{"cx":"12","cy":"12","r":"3"}]];
const SHAPES: ChromeIconNode = [["path",{"d":"M8.3 10a.7.7 0 0 1-.626-1.079L11.4 3a.7.7 0 0 1 1.198-.043L16.3 8.9a.7.7 0 0 1-.572 1.1Z"}],["rect",{"x":"3","y":"14","width":"7","height":"7","rx":"1"}],["circle",{"cx":"17.5","cy":"17.5","r":"3.5"}]];
const SHARE: ChromeIconNode = [["path",{"d":"M12 2v13"}],["path",{"d":"m16 6-4-4-4 4"}],["path",{"d":"M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"}]];
const SHARE_2: ChromeIconNode = [["circle",{"cx":"18","cy":"5","r":"3"}],["circle",{"cx":"6","cy":"12","r":"3"}],["circle",{"cx":"18","cy":"19","r":"3"}],["line",{"x1":"8.59","x2":"15.42","y1":"13.51","y2":"17.49"}],["line",{"x1":"15.41","x2":"8.59","y1":"6.51","y2":"10.49"}]];
const SHIELD: ChromeIconNode = [["path",{"d":"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"}]];
const SHOPPING_CART: ChromeIconNode = [["circle",{"cx":"8","cy":"21","r":"1"}],["circle",{"cx":"19","cy":"21","r":"1"}],["path",{"d":"M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"}]];
const SLIDERS_HORIZONTAL: ChromeIconNode = [["path",{"d":"M10 5H3"}],["path",{"d":"M12 19H3"}],["path",{"d":"M14 3v4"}],["path",{"d":"M16 17v4"}],["path",{"d":"M21 12h-9"}],["path",{"d":"M21 19h-5"}],["path",{"d":"M21 5h-7"}],["path",{"d":"M8 10v4"}],["path",{"d":"M8 12H3"}]];
const SPACE: ChromeIconNode = [["path",{"d":"M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1"}]];
const SPARKLES: ChromeIconNode = [["path",{"d":"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z"}],["path",{"d":"M20 2v4"}],["path",{"d":"M22 4h-4"}],["circle",{"cx":"4","cy":"20","r":"2"}]];
const SPLIT: ChromeIconNode = [["path",{"d":"M16 3h5v5"}],["path",{"d":"M8 3H3v5"}],["path",{"d":"M12 22v-8.3a4 4 0 0 0-1.172-2.872L3 3"}],["path",{"d":"m15 9 6-6"}]];
const SQUARE: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}]];
const SQUARE_CHECK: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"m9 12 2 2 4-4"}]];
const SQUARE_CODE: ChromeIconNode = [["path",{"d":"m10 9-3 3 3 3"}],["path",{"d":"m14 15 3-3-3-3"}],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"}]];
const SQUARE_PEN: ChromeIconNode = [["path",{"d":"M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"}],["path",{"d":"M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z"}]];
const SQUARE_PLUS: ChromeIconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M8 12h8"}],["path",{"d":"M12 8v8"}]];
const STAMP: ChromeIconNode = [["path",{"d":"M14 13V8.5C14 7 15 7 15 5a3 3 0 0 0-6 0c0 2 1 2 1 3.5V13"}],["path",{"d":"M20 15.5a2.5 2.5 0 0 0-2.5-2.5h-11A2.5 2.5 0 0 0 4 15.5V17a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1z"}],["path",{"d":"M5 22h14"}]];
const STAR_HALF: ChromeIconNode = [["path",{"d":"M12 18.338a2.1 2.1 0 0 0-.987.244L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.12 2.12 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.12 2.12 0 0 0 1.597-1.16l2.309-4.679A.53.53 0 0 1 12 2"}]];
const STRETCH_HORIZONTAL: ChromeIconNode = [["rect",{"width":"20","height":"6","x":"2","y":"4","rx":"2"}],["rect",{"width":"20","height":"6","x":"2","y":"14","rx":"2"}]];
const SUN: ChromeIconNode = [["circle",{"cx":"12","cy":"12","r":"4"}],["path",{"d":"M12 2v2"}],["path",{"d":"M12 20v2"}],["path",{"d":"m4.93 4.93 1.41 1.41"}],["path",{"d":"m17.66 17.66 1.41 1.41"}],["path",{"d":"M2 12h2"}],["path",{"d":"M20 12h2"}],["path",{"d":"m6.34 17.66-1.41 1.41"}],["path",{"d":"m19.07 4.93-1.41 1.41"}]];
const TABLE: ChromeIconNode = [["path",{"d":"M12 3v18"}],["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M3 9h18"}],["path",{"d":"M3 15h18"}]];
const TABLE_2: ChromeIconNode = [["path",{"d":"M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18"}]];
const TABLE_ROWS_SPLIT: ChromeIconNode = [["path",{"d":"M14 10h2"}],["path",{"d":"M15 22v-8"}],["path",{"d":"M15 2v4"}],["path",{"d":"M2 10h2"}],["path",{"d":"M20 10h2"}],["path",{"d":"M3 19h18"}],["path",{"d":"M3 22v-6a2 2 135 0 1 2-2h14a2 2 45 0 1 2 2v6"}],["path",{"d":"M3 2v2a2 2 45 0 0 2 2h14a2 2 135 0 0 2-2V2"}],["path",{"d":"M8 10h2"}],["path",{"d":"M9 22v-8"}],["path",{"d":"M9 2v4"}]];
const TAG: ChromeIconNode = [["path",{"d":"M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z"}],["circle",{"cx":"7.5","cy":"7.5","r":".5","fill":"currentColor"}]];
const TAGS: ChromeIconNode = [["path",{"d":"M13.172 2a2 2 0 0 1 1.414.586l6.71 6.71a2.4 2.4 0 0 1 0 3.408l-4.592 4.592a2.4 2.4 0 0 1-3.408 0l-6.71-6.71A2 2 0 0 1 6 9.172V3a1 1 0 0 1 1-1z"}],["path",{"d":"M2 7v6.172a2 2 0 0 0 .586 1.414l6.71 6.71a2.4 2.4 0 0 0 3.191.193"}],["circle",{"cx":"10.5","cy":"6.5","r":".5","fill":"currentColor"}]];
const TERMINAL: ChromeIconNode = [["path",{"d":"M12 19h8"}],["path",{"d":"m4 17 6-6-6-6"}]];
const TEXT: ChromeIconNode = [["path",{"d":"M21 5H3"}],["path",{"d":"M15 12H3"}],["path",{"d":"M17 19H3"}]];
const TEXT_ALIGN_CENTER: ChromeIconNode = [["path",{"d":"M21 5H3"}],["path",{"d":"M17 12H7"}],["path",{"d":"M19 19H5"}]];
const TEXT_ALIGN_END: ChromeIconNode = [["path",{"d":"M21 5H3"}],["path",{"d":"M21 12H9"}],["path",{"d":"M21 19H7"}]];
const TEXT_ALIGN_JUSTIFY: ChromeIconNode = [["path",{"d":"M3 5h18"}],["path",{"d":"M3 12h18"}],["path",{"d":"M3 19h18"}]];
const TEXT_ALIGN_START: ChromeIconNode = [["path",{"d":"M21 5H3"}],["path",{"d":"M15 12H3"}],["path",{"d":"M17 19H3"}]];
const TEXT_CURSOR: ChromeIconNode = [["path",{"d":"M17 22h-1a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4h1"}],["path",{"d":"M7 22h1a4 4 0 0 0 4-4v-1"}],["path",{"d":"M7 2h1a4 4 0 0 1 4 4v1"}]];
const TEXT_CURSOR_INPUT: ChromeIconNode = [["path",{"d":"M12 20h-1a2 2 0 0 1-2-2 2 2 0 0 1-2 2H6"}],["path",{"d":"M13 8h7a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-7"}],["path",{"d":"M5 16H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h1"}],["path",{"d":"M6 4h1a2 2 0 0 1 2 2 2 2 0 0 1 2-2h1"}],["path",{"d":"M9 6v12"}]];
const THERMOMETER: ChromeIconNode = [["path",{"d":"M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z"}]];
const TOGGLE_RIGHT: ChromeIconNode = [["circle",{"cx":"15","cy":"12","r":"3"}],["rect",{"width":"20","height":"14","x":"2","y":"5","rx":"7"}]];
const TRASH_2: ChromeIconNode = [["path",{"d":"M10 11v6"}],["path",{"d":"M14 11v6"}],["path",{"d":"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"}],["path",{"d":"M3 6h18"}],["path",{"d":"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"}]];
const TRENDING_UP: ChromeIconNode = [["path",{"d":"M16 7h6v6"}],["path",{"d":"m22 7-8.5 8.5-5-5L2 17"}]];
const TRIANGLE_ALERT: ChromeIconNode = [["path",{"d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"}],["path",{"d":"M12 9v4"}],["path",{"d":"M12 17h.01"}]];
const TYPE: ChromeIconNode = [["path",{"d":"M12 4v16"}],["path",{"d":"M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2"}],["path",{"d":"M9 20h6"}]];
const UNDO_2: ChromeIconNode = [["path",{"d":"M9 14 4 9l5-5"}],["path",{"d":"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11"}]];
const UNFOLD_VERTICAL: ChromeIconNode = [["path",{"d":"M12 22v-6"}],["path",{"d":"M12 8V2"}],["path",{"d":"M4 12H2"}],["path",{"d":"M10 12H8"}],["path",{"d":"M16 12h-2"}],["path",{"d":"M22 12h-2"}],["path",{"d":"m15 19-3 3-3-3"}],["path",{"d":"m15 5-3-3-3 3"}]];
const UNLINK: ChromeIconNode = [["path",{"d":"m18.84 12.25 1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71"}],["path",{"d":"m5.17 11.75-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71"}],["line",{"x1":"8","x2":"8","y1":"2","y2":"5"}],["line",{"x1":"2","x2":"5","y1":"8","y2":"8"}],["line",{"x1":"16","x2":"16","y1":"19","y2":"22"}],["line",{"x1":"19","x2":"22","y1":"16","y2":"16"}]];
const UPLOAD: ChromeIconNode = [["path",{"d":"M12 3v12"}],["path",{"d":"m17 8-5-5-5 5"}],["path",{"d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"}]];
const USER: ChromeIconNode = [["path",{"d":"M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"}],["circle",{"cx":"12","cy":"7","r":"4"}]];
const USERS: ChromeIconNode = [["path",{"d":"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"}],["path",{"d":"M16 3.128a4 4 0 0 1 0 7.744"}],["path",{"d":"M22 21v-2a4 4 0 0 0-3-3.87"}],["circle",{"cx":"9","cy":"7","r":"4"}]];
const WAND_SPARKLES: ChromeIconNode = [["path",{"d":"m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72"}],["path",{"d":"m14 7 3 3"}],["path",{"d":"M5 6v4"}],["path",{"d":"M19 14v4"}],["path",{"d":"M10 2v2"}],["path",{"d":"M7 8H3"}],["path",{"d":"M21 16h-4"}],["path",{"d":"M11 3H9"}]];
const X: ChromeIconNode = [["path",{"d":"M18 6 6 18"}],["path",{"d":"m6 6 12 12"}]];
const ZAP: ChromeIconNode = [["path",{"d":"M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"}]];

/** Drawn for a name with no entry. */
export const CHROME_ICON_FALLBACK: ChromeIconNode = CIRCLE_DASHED;

/** Material Symbols name: the drawing of the closest lucide icon. */
export const CHROME_ICON_NODES: Readonly<Record<string, ChromeIconNode>> = {
  menu: MENU, // menu
  edit_square: SQUARE_PEN, // square-pen
  palette: PALETTE, // palette
  ios_share: SHARE, // share
  share: SHARE_2, // share-2
  expand_less: CHEVRON_UP, // chevron-up
  expand_more: CHEVRON_DOWN, // chevron-down
  check: CHECK, // check
  warning: TRIANGLE_ALERT, // triangle-alert
  link: LINK, // link
  link_off: UNLINK, // unlink
  hourglass_top: HOURGLASS, // hourglass
  hourglass_empty: HOURGLASS, // hourglass
  download: DOWNLOAD, // download
  downloading: LOADER, // loader
  code_blocks: SQUARE_CODE, // square-code
  drag_indicator: GRIP_VERTICAL, // grip-vertical
  forum: MESSAGES_SQUARE, // messages-square
  add_photo_alternate: IMAGE_PLUS, // image-plus
  close: X, // x
  error: CIRCLE_ALERT, // circle-alert
  image: IMAGE, // image
  arrow_forward: ARROW_RIGHT, // arrow-right
  dashboard: LAYOUT_DASHBOARD, // layout-dashboard
  dock_to_left: PANEL_LEFT, // panel-left
  dock_to_right: PANEL_RIGHT, // panel-right
  picture_in_picture: PICTURE_IN_PICTURE_2, // picture-in-picture-2
  tune: SLIDERS_HORIZONTAL, // sliders-horizontal
  grid_view: LAYOUT_GRID, // layout-grid
  edit: PENCIL, // pencil
  send: SEND_HORIZONTAL, // send-horizontal
  chevron_left: CHEVRON_LEFT, // chevron-left
  chevron_right: CHEVRON_RIGHT, // chevron-right
  folder_open: FOLDER_OPEN, // folder-open
  content_copy: COPY, // copy
  search: SEARCH, // search
  unfold_less: CHEVRONS_DOWN_UP, // chevrons-down-up
  unfold_more: CHEVRONS_UP_DOWN, // chevrons-up-down
  history: HISTORY, // history
  check_circle: CIRCLE_CHECK, // circle-check
  add_circle: CIRCLE_PLUS, // circle-plus
  chat_bubble: MESSAGE_SQUARE, // message-square
  chat_bubble_outline: MESSAGE_SQUARE_DASHED, // message-square-dashed
  chat: MESSAGE_SQUARE_TEXT, // message-square-text
  bookmark_border: BOOKMARK, // bookmark
  dark_mode: MOON, // moon
  light_mode: SUN, // sun
  view_quilt: LAYOUT_TEMPLATE, // layout-template
  auto_awesome: SPARKLES, // sparkles
  bolt: ZAP, // zap
  code: CODE, // code
  language: GLOBE, // globe
  folder_zip: FOLDER_ARCHIVE, // folder-archive
  shapes: SHAPES, // shapes
  category: SHAPES, // shapes
  data_object: BRACES, // braces
  design_services: PENCIL_RULER, // pencil-ruler
  magic_button: WAND_SPARKLES, // wand-sparkles
  info: INFO, // info
  terminal: TERMINAL, // terminal
  visibility: EYE, // eye
  undo: UNDO_2, // undo-2
  redo: REDO_2, // redo-2
  more_horiz: ELLIPSIS, // ellipsis
  fit_screen: MAXIMIZE, // maximize
  density_medium: ROWS_3, // rows-3
  view_column: COLUMNS_3, // columns-3
  view_week: COLUMNS_4, // columns-4
  compare: COLUMNS_2, // columns-2
  check_box: SQUARE_CHECK, // square-check
  check_box_outline_blank: SQUARE, // square
  refresh: REFRESH_CW, // refresh-cw
  open_in_new: EXTERNAL_LINK, // external-link
  add: PLUS, // plus
  table_view: TABLE_2, // table-2
  upload: UPLOAD, // upload
  restart_alt: ROTATE_CCW, // rotate-ccw
  radio_button_checked: CIRCLE_DOT, // circle-dot
  delete: TRASH_2, // trash-2
  arrow_upward: ARROW_UP, // arrow-up
  arrow_downward: ARROW_DOWN, // arrow-down
  width: MOVE_HORIZONTAL, // move-horizontal
  height: MOVE_VERTICAL, // move-vertical
  width_full: STRETCH_HORIZONTAL, // stretch-horizontal
  swap_horiz: ARROW_LEFT_RIGHT, // arrow-left-right
  compare_arrows: ARROW_LEFT_RIGHT, // arrow-left-right
  view_agenda: ROWS_2, // rows-2
  call_split: SPLIT, // split
  open_with: MOVE, // move
  drag_pan: MOVE, // move
  crop_free: SCAN, // scan
  north: ARROW_UP_TO_LINE, // arrow-up-to-line
  west: ARROW_LEFT_TO_LINE, // arrow-left-to-line
  south: ARROW_DOWN_TO_LINE, // arrow-down-to-line
  top_panel_open: PANEL_TOP, // panel-top
  left_panel_open: PANEL_LEFT, // panel-left
  bottom_panel_open: PANEL_BOTTOM, // panel-bottom
  reorder: ALIGN_JUSTIFY, // align-justify
  align_horizontal_left: ALIGN_START_VERTICAL, // align-start-vertical
  align_horizontal_center: ALIGN_CENTER_VERTICAL, // align-center-vertical
  align_horizontal_right: ALIGN_END_VERTICAL, // align-end-vertical
  align_vertical_top: ALIGN_START_HORIZONTAL, // align-start-horizontal
  align_vertical_center: ALIGN_CENTER_HORIZONTAL, // align-center-horizontal
  align_vertical_bottom: ALIGN_END_HORIZONTAL, // align-end-horizontal
  vertical_align_top: ARROW_UP_TO_LINE, // arrow-up-to-line
  vertical_align_center: FOLD_VERTICAL, // fold-vertical
  vertical_align_bottom: ARROW_DOWN_TO_LINE, // arrow-down-to-line
  expand: UNFOLD_VERTICAL, // unfold-vertical
  format_align_left: TEXT_ALIGN_START, // text-align-start
  format_align_center: TEXT_ALIGN_CENTER, // text-align-center
  format_align_right: TEXT_ALIGN_END, // text-align-end
  rocket_launch: ROCKET, // rocket
  list_alt: CLIPBOARD_LIST, // clipboard-list
  shopping_cart: SHOPPING_CART, // shopping-cart
  article: NEWSPAPER, // newspaper
  wallpaper: IMAGES, // images
  smart_button: RECTANGLE_HORIZONTAL, // rectangle-horizontal
  table_chart: TABLE, // table
  text_fields: TYPE, // type
  tab: APP_WINDOW, // app-window
  toggle_on: TOGGLE_RIGHT, // toggle-right
  new_releases: BADGE, // badge
  group: USERS, // users
  analytics: CHART_NO_AXES_COLUMN, // chart-no-axes-column
  arrow_drop_down_circle: CIRCLE_CHEVRON_DOWN, // circle-chevron-down
  calendar_today: CALENDAR, // calendar
  ads_click: MOUSE_POINTER_CLICK, // mouse-pointer-click
  title: HEADING, // heading
  edit_note: TEXT_CURSOR_INPUT, // text-cursor-input
  add_box: SQUARE_PLUS, // square-plus
  remove: MINUS, // minus
  block: BAN, // ban
  colorize: PIPETTE, // pipette
  contrast: CONTRAST, // contrast
  delete_sweep: LIST_X, // list-x
  format_color_fill: PAINT_BUCKET, // paint-bucket
  view_module: GRID_3X3, // grid-3x3
  widgets: BLOCKS, // blocks
  monitoring: CHART_NO_AXES_COMBINED, // chart-no-axes-combined
  settings: SETTINGS, // settings
  contacts: CONTACT, // contact
  login: LOG_IN, // log-in
  shield: SHIELD, // shield
  trending_up: TRENDING_UP, // trending-up
  eco: LEAF, // leaf
  thermostat: THERMOMETER, // thermometer
  filter_alt: FUNNEL, // funnel
  candlestick_chart: CHART_CANDLESTICK, // chart-candlestick
  report: OCTAGON_ALERT, // octagon-alert
  fact_check: CLIPBOARD_CHECK, // clipboard-check
  home: HOUSE, // house
  database: DATABASE, // database
  person: USER, // user
  notifications: BELL, // bell
  bar_chart: CHART_COLUMN, // chart-column
  account_circle: CIRCLE_USER, // circle-user
  account_tree: NETWORK, // network
  area_chart: CHART_AREA, // chart-area
  badge: ID_CARD, // id-card
  branding_watermark: STAMP, // stamp
  circle: CIRCLE, // circle
  contact_page: FILE_USER, // file-user
  counter_1: HASH, // hash
  credit_card: CREDIT_CARD, // credit-card
  donut_large: CIRCLE_DASHED, // circle-dashed
  grid_on: GRID_2X2, // grid-2x2
  insert_chart: CHART_COLUMN_BIG, // chart-column-big
  inventory_2: PACKAGE, // package
  label: TAG, // tag
  list: LIST, // list
  menu_open: PANEL_LEFT_CLOSE, // panel-left-close
  multiline_chart: CHART_LINE, // chart-line
  notes: TEXT, // text
  percent: PERCENT, // percent
  pie_chart: CHART_PIE, // chart-pie
  pin: BINARY, // binary
  radar: RADAR, // radar
  scatter_plot: CHART_SCATTER, // chart-scatter
  segment: LIST_FILTER, // list-filter
  sell: TAGS, // tags
  short_text: MINUS, // minus
  show_chart: CHART_SPLINE, // chart-spline
  space_bar: SPACE, // space
  speed: GAUGE, // gauge
  ssid_chart: CHART_NO_AXES_COMBINED, // chart-no-axes-combined
  stacked_bar_chart: CHART_COLUMN_STACKED, // chart-column-stacked
  star_half: STAR_HALF, // star-half
  subject: TEXT_ALIGN_JUSTIFY, // text-align-justify
  table_rows: TABLE_ROWS_SPLIT, // table-rows-split
  timeline: CHART_GANTT, // chart-gantt
  upload_file: FILE_UP, // file-up
  verified: BADGE_CHECK, // badge-check
  waterfall_chart: CHART_COLUMN_DECREASING, // chart-column-decreasing
  web_asset: PANEL_TOP_DASHED, // panel-top-dashed
  input: TEXT_CURSOR, // text-cursor
  dashboard_customize: LAYOUT_PANEL_TOP, // layout-panel-top
};
