/* ── Shared component ID ↔ block type mappings ── */

/** Map store component IDs to block type strings.
 *  Wizard IDs now point to INDIVIDUAL block types (not compound groups)
 *  so each block can be selected, swapped, or removed independently. */
export const ID_TO_BLOCK: Record<string, string> = {
  /* Wizard IDs → individual Simulated blocks */
  buttons: "SimulatedButton",
  cards: "SimulatedCard",
  table: "SimulatedDataTable",
  inputs: "SimulatedTextInput",
  "text-fields": "SimulatedTextInput",
  "form-field": "SimulatedTextInput",
  tabs: "SimulatedTabs",
  switches: "SimulatedSwitch",
  checkboxes: "SimulatedCheckbox",
  radios: "SimulatedSwitch",
  badges: "SimulatedBadge",
  avatars: "SimulatedAvatar",
  alerts: "Alert",
  "progress-bar": "SimulatedProgress",
  tooltips: "SimulatedTooltip",
  progress: "SimulatedStatCard",
  typography: "SimulatedTitle",

  /* Direct Simulated IDs (unchanged) */
  "sim-button": "SimulatedButton",
  "sim-title": "SimulatedTitle",
  "sim-text-input": "SimulatedTextInput",
  "sim-alert": "Alert",
  "sim-data-table": "SimulatedDataTable",
  "sim-accordion": "SimulatedAccordion",
  "sim-breadcrumb": "SimulatedBreadcrumb",
  "sim-card": "SimulatedCard",
  "sim-badge": "SimulatedBadge",
  "sim-chat-message": "SimulatedChatMessage",
  "sim-chart": "SimulatedChart",
  "sim-stat-card": "SimulatedStatCard",
  "sim-radio-group": "SimulatedRadioGroup",
  "sim-slider": "SimulatedSlider",
  "sim-number-input": "SimulatedNumberInput",
  "sim-multiline-input": "SimulatedMultilineInput",
  "sim-pill": "SimulatedPill",
  "sim-toggle-button": "SimulatedToggleButton",
  "sim-segmented-group": "SimulatedSegmentedGroup",
  "sim-link": "SimulatedLink",
  "sim-listbox": "SimulatedListBox",
  "sim-combobox": "SimulatedComboBox",
  "sim-file-drop": "SimulatedFileDropZone",
  "sim-tree": "SimulatedTree",
  "sim-rating": "SimulatedRating",
  "sim-skeleton": "SimulatedSkeleton",
  "sim-searchbox": "SimulatedSearchbox",
  "sim-tokenized-input": "SimulatedTokenizedInput",
  "sim-nav-drawer": "SimulatedNavDrawer",
  "sim-popover": "SimulatedPopover",
  "sim-persona": "SimulatedPersona",
  "sim-avatar-group": "SimulatedAvatarGroup",
};

/** Compound expansion: some wizard IDs produce multiple individual blocks.
 *  Each entry defines the block type + unique default props for each instance. */
export const ID_TO_MULTI_BLOCKS: Record<string, { type: string; props: Record<string, unknown> }[]> = {
  progress: [
    { type: "SimulatedStatCard", props: { label: "Revenue", value: "$42.8K", pct: 60, colSpan: 1 } },
    { type: "SimulatedStatCard", props: { label: "Users", value: "1,247", pct: 75, colSpan: 1 } },
    { type: "SimulatedStatCard", props: { label: "Growth", value: "+18%", pct: 90, colSpan: 1 } },
  ],
  buttons: [
    { type: "SimulatedButton", props: { variant: "primary", label: "Primary" } },
    { type: "SimulatedButton", props: { variant: "secondary", label: "Secondary" } },
  ],
  cards: [
    { type: "SimulatedCard", props: { title: "Analytics", content: "Track key metrics and performance indicators." } },
    { type: "SimulatedCard", props: { title: "Reports", content: "Generate and export detailed reports." } },
  ],
  badges: [
    { type: "SimulatedBadge", props: { label: "Active", status: "success" } },
    { type: "SimulatedBadge", props: { label: "Pending", status: "warning" } },
    { type: "SimulatedBadge", props: { label: "Closed", status: "default" } },
  ],
};

/** Reverse: block type → canonical store ID */
export const BLOCK_TO_ID: Record<string, string> = {
  /* Legacy compound types (still valid for reverse lookup) */
  Buttons: "buttons",
  Cards: "cards",
  DataTable: "table",
  FormFields: "inputs",
  Tabs: "tabs",
  Toggles: "switches",
  Badges: "badges",
  Avatars: "avatars",
  Alert: "alerts",
  Progress: "progress-bar",
  Tooltips: "tooltips",
  StatsCards: "progress",
  Dialog: "dialog",
  Dropdown: "dropdown",
  DatePicker: "date-picker",
  Typography: "typography",

  /* Individual Simulated types */
  SimulatedButton: "buttons",
  SimulatedTitle: "typography",
  SimulatedTextInput: "inputs",
  SimulatedAlert: "sim-alert",  /* legacy alias */
  SimulatedDataTable: "table",
  SimulatedAccordion: "sim-accordion",
  SimulatedBreadcrumb: "sim-breadcrumb",
  SimulatedCard: "cards",
  SimulatedBadge: "badges",
  SimulatedChatMessage: "sim-chat-message",
  SimulatedChart: "sim-chart",
  SimulatedStatCard: "progress",
  SimulatedRadioGroup: "sim-radio-group",
  SimulatedSlider: "sim-slider",
  SimulatedNumberInput: "sim-number-input",
  SimulatedMultilineInput: "sim-multiline-input",
  SimulatedPill: "sim-pill",
  SimulatedToggleButton: "sim-toggle-button",
  SimulatedSegmentedGroup: "sim-segmented-group",
  SimulatedLink: "sim-link",
  SimulatedListBox: "sim-listbox",
  SimulatedComboBox: "sim-combobox",
  SimulatedFileDropZone: "sim-file-drop",
  SimulatedTree: "sim-tree",
  SimulatedRating: "sim-rating",
  SimulatedSkeleton: "sim-skeleton",
  SimulatedSearchbox: "sim-searchbox",
  SimulatedTokenizedInput: "sim-tokenized-input",
  SimulatedNavDrawer: "sim-nav-drawer",
  SimulatedPopover: "sim-popover",
  SimulatedPersona: "sim-persona",
  SimulatedAvatarGroup: "sim-avatar-group",
  SimulatedCheckbox: "checkboxes",
  SimulatedSwitch: "switches",
  SimulatedDropdown: "dropdown",
  SimulatedProgress: "progress-bar",
  SimulatedAvatar: "avatars",
  SimulatedTabs: "tabs",
  SimulatedDialog: "dialog",
  SimulatedTooltip: "tooltips",
  SimulatedDatePicker: "date-picker",
};
