/* ── Shared component ID ↔ block type mappings ── */

/** Map store component IDs to block type strings */
export const ID_TO_BLOCK: Record<string, string> = {
  buttons: "Buttons",
  cards: "Cards",
  table: "DataTable",
  inputs: "FormFields",
  "text-fields": "FormFields",
  "form-field": "FormFields",
  tabs: "Tabs",
  switches: "Toggles",
  checkboxes: "Toggles",
  radios: "Toggles",
  badges: "Badges",
  avatars: "Avatars",
  alerts: "Alert",
  "progress-bar": "Progress",
  tooltips: "Tooltips",
  progress: "StatsCards",
  typography: "Typography",
  "sim-button": "SimulatedButton",
  "sim-title": "SimulatedTitle",
  "sim-text-input": "SimulatedTextInput",
  "sim-alert": "SimulatedAlert",
  "sim-data-table": "SimulatedDataTable",
  "sim-accordion": "SimulatedAccordion",
  "sim-breadcrumb": "SimulatedBreadcrumb",
  "sim-card": "SimulatedCard",
  "sim-badge": "SimulatedBadge",
};

/** Reverse: block type → canonical store ID */
export const BLOCK_TO_ID: Record<string, string> = {
  Buttons: "buttons",
  Cards: "cards",
  DataTable: "table",
  FormFields: "inputs",
  Tabs: "tabs",
  Toggles: "switches",
  Badges: "badges",
  Avatars: "avatars",
  Alert: "alerts",
  Progress: "progress-bar",
  Tooltips: "tooltips",
  StatsCards: "progress",
  Dialog: "dialog",
  Dropdown: "dropdown",
  DatePicker: "date-picker",
  Typography: "typography",
  SimulatedButton: "sim-button",
  SimulatedTitle: "sim-title",
  SimulatedTextInput: "sim-text-input",
  SimulatedAlert: "sim-alert",
  SimulatedDataTable: "sim-data-table",
  SimulatedAccordion: "sim-accordion",
  SimulatedBreadcrumb: "sim-breadcrumb",
  SimulatedCard: "sim-card",
  SimulatedBadge: "sim-badge",
};
