import { test, expect } from '@playwright/test';

test('Allocation inspector updates donut to pie and back without stale geometry or labels', async ({ page }) => {
  await page.route('**/api/health', route => route.fulfill({ json: { anthropicConfigured: false, firebaseConfigured: false } }));
  await page.goto('/builder');
  await page.getByRole('button', { name: /Browse templates/ }).click();
  await page.getByRole('button', { name: 'Use the Performance Analytics template' }).click();
  await page.getByRole('button', { name: 'Edit canvas', exact: true }).click();
  const block = page.locator('[data-block-id="tpl-perf-allocation"]');
  await block.focus();
  await block.press('Enter');
  const show = page.getByRole('button', { name: 'Show component library', exact: true });
  if (await show.isVisible()) await show.click();
  const slice = block.locator('.highcharts-pie-series .highcharts-point').first();
  const arcCount = async () => [...((await slice.getAttribute('d')) ?? '').matchAll(/\bA\s+([\d.e+-]+)/g)].filter(match => Number(match[1]) > 0.01).length;
  await expect.poll(arcCount).toBe(2);
  await expect(block.locator('svg text').filter({ hasText: '£3.55bn' })).toBeVisible();
  const parts = await block.locator('.highcharts-legend-item').allTextContents();
  await page.getByRole('combobox', { name: 'Chart type', exact: true }).click();
  await page.getByRole('option', { name: 'Pie', exact: true }).click();
  await expect.poll(arcCount).toBe(1);
  await expect(block.locator('svg text').filter({ hasText: '£3.55bn' })).toHaveCount(0);
  await expect(block.locator('.highcharts-legend-item')).toHaveText(parts);
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Portfolio composition');
  await expect(block.locator('.dh-panel-title')).toHaveText('Portfolio composition');
  await page.getByRole('combobox', { name: 'Chart type', exact: true }).click();
  await page.getByRole('option', { name: 'Donut', exact: true }).click();
  await expect.poll(arcCount).toBe(2);
  await expect(block.locator('svg text').filter({ hasText: '£3.55bn' })).toBeVisible();
  await expect(block.locator('.highcharts-legend-item')).toHaveText(parts);
  await page.getByRole('textbox', { name: 'Centre label (donut)' }).fill('Portfolio');
  await expect(block.locator('svg text').filter({ hasText: /^Portfolio$/ })).toBeVisible();
  const height = page.getByRole('slider', { name: /^Height/ });
  await height.fill('500');
  await expect(block.locator('.dh-panel')).toHaveCSS('height', '500px');
  const frame = page.getByRole('switch', { name: 'Framed panel' });
  await frame.click();
  await expect(block.locator('.dh-panel')).toHaveCount(0);
  await expect(block.locator('.highcharts-title')).toHaveText('Portfolio composition');
  await frame.click();
  await expect(block.locator('.dh-panel')).toHaveCSS('height', '500px');
  await page.getByRole('combobox', { name: 'Chart type', exact: true }).click();
  await page.getByRole('option', { name: 'Pie', exact: true }).click();
  await expect.poll(arcCount).toBe(1);
  await page.reload();
  await expect(block.locator('.dh-panel-title')).toHaveText('Portfolio composition');
  await expect(block.locator('.dh-panel')).toHaveCSS('height', '500px');
  await expect.poll(arcCount).toBe(1);
  await expect(block.locator('.highcharts-legend-item')).toHaveText(parts);
  await expect(block.locator('svg text').filter({ hasText: /^Portfolio$/ })).toHaveCount(0);
});
